import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { MapContainer, TileLayer, Polyline, CircleMarker, Popup, useMap } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, CloudRain, Filter, Globe2, LocateFixed, Menu, Navigation, Plus, Radio, Send, Truck, UploadCloud, X } from "lucide-react";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const copy = { en: { overview:"Operational overview", routes:"Routes", alerts:"Alerts", vehicles:"Vehicles", report:"Field report", live:"LIVE NETWORK", sync:"Last sync", state:"State", role:"Role", manager:"Logistics manager", all:"All states", submit:"Submit report", incident:"Incident type", severity:"Severity", notes:"Field notes", location:"Location", upload:"Upload damage photo", routeHealth:"Route health", bottlenecks:"Top bottlenecks", tracking:"Live delivery tracking", watch:"Watch the network update", rerouted:"REROUTED", inTransit:"IN TRANSIT", delivered:"DELIVERED" }, as: { overview:"কাৰ্যকৰী পৰ্যবেক্ষণ", routes:"পথসমূহ", alerts:"সতৰ্কবাণী", vehicles:"যানবাহন", report:"ক্ষেত্ৰ প্ৰতিবেদন", live:"লাইভ নেটৱৰ্ক", sync:"শেষ সমন্বয়", state:"ৰাজ্য", role:"ভূমিকা", manager:"লজিষ্টিক মেনেজাৰ", all:"সকলো ৰাজ্য", submit:"প্ৰতিবেদন পঠিয়াওক", incident:"ঘটনাৰ ধৰণ", severity:"তীব্ৰতা", notes:"ক্ষেত্ৰৰ টোকা", location:"স্থান", upload:"ক্ষতিৰ ফটো আপলোড কৰক", routeHealth:"পথৰ অৱস্থা", bottlenecks:"মুখ্য বাধা", tracking:"লাইভ ডেলিভাৰী অনুসৰণ", watch:"নেটৱৰ্কৰ পৰিৱৰ্তন চাওক", rerouted:"পুনৰ পথ নিৰ্ধাৰিত", inTransit:"পথত আছে", delivered:"ডেলিভাৰ কৰা হৈছে" } };
const riskColor = (risk) => risk > 60 ? "#f43f5e" : risk > 35 ? "#f59e0b" : "#10b981";

function Recenter({ position }) { const map = useMap(); useEffect(() => { map.setView(position, 7); }, [map, position]); return null; }

const Home = () => {
  const [data, setData] = useState(null); const [lang, setLang] = useState("en"); const [state, setState] = useState("All states"); const [role, setRole] = useState("Logistics manager"); const [showReport, setShowReport] = useState(false); const [toast, setToast] = useState(""); const [form, setForm] = useState({ incident_type:"Landslide", severity:"High", state:"Assam", notes:"", latitude:25.57, longitude:91.88, image_data:null });
  const t = copy[lang];
  const load = async () => { try { const result = await axios.get(`${API}/overview`); setData(result.data); } catch { setToast("Unable to reach the demo service"); } };
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  const filteredRoutes = useMemo(() => data?.routes.filter(r => state === "All states" || r.state === state) || [], [data, state]);
  const filteredVehicles = useMemo(() => data?.vehicles.filter(v => state === "All states" || v.state === state) || [], [data, state]);
  const submitReport = async (e) => { e.preventDefault(); try { const result = await axios.post(`${API}/reports`, form); setToast(result.data.alert); setShowReport(false); await load(); } catch { setToast("Report saved offline — sync pending"); } setTimeout(() => setToast(""), 5000); };
  if (!data) return <div className="loading-screen"><div className="brand-mark">N</div><p>Loading regional network…</p></div>;
  const tRisk = data.routes.reduce((a, r) => a + r.risk, 0) / data.routes.length;
  const activeIncidents = data.incidents.filter(i => state === "All states" || i.state === state);
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">N</div><div><strong>NE—LOGIX</strong><span>ACCESSIBILITY INTELLIGENCE</span></div></div><div className="topbar-actions"><div className="live-pill"><i></i>{t.live}</div><button className="icon-button" aria-label="Open navigation" data-testid="navigation-menu-button"><Menu size={18}/></button><button className="language-button" onClick={() => setLang(lang === "en" ? "as" : "en")} data-testid="language-toggle"><Globe2 size={15}/>{lang === "en" ? "অসমীয়া" : "EN"}</button><div className="profile"><div className="avatar">AK</div><span>Arun K.</span><span className="chevron">⌄</span></div></div></header>
    <section className="page-wrap"><div className="intro-row"><div><div className="eyebrow"><span className="eyebrow-line"></span>{t.overview} / 06:42 UTC</div><h1>Move what matters.<br/><em>Know what’s ahead.</em></h1><p className="intro-copy">A live intelligence layer for essential goods moving across the North East.</p></div><div className="intro-controls"><label>{t.role}<select value={role} onChange={e => setRole(e.target.value)} data-testid="role-filter"><option>Logistics manager</option><option>Field officer</option><option>District administrator</option></select></label><button className="primary-button" onClick={() => setShowReport(true)} data-testid="open-field-report-button"><Plus size={17}/> {t.report}</button></div></div>
      <div className="metric-strip"><Metric icon={<Truck/>} label={t.vehicles} value="06" detail="05 in motion" tone="orange"/><Metric icon={<Navigation/>} label={t.routes} value="07" detail="02 need attention" tone="green"/><Metric icon={<AlertTriangle/>} label={t.alerts} value="03" detail="01 high priority" tone="rose"/><Metric icon={<Activity/>} label="On-time rate" value="87.4%" detail="↑ 4.8% this week" tone="blue"/><div className="uptime"><span>System uptime</span><strong>{data.uptime}</strong><small><i></i> {t.sync} {data.sync_time}</small></div></div>
      <div className="filter-row"><div className="filter-heading"><Filter size={15}/> {t.state}</div><div className="filter-pills">{["All states", ...data.states].map(s => <button key={s} className={state === s ? "filter-pill active" : "filter-pill"} onClick={() => setState(s)} data-testid={`state-filter-${s.toLowerCase().replaceAll(" ","-")}`}>{s}</button>)}</div><button className="filter-icon" data-testid="filter-options-button"><Filter size={15}/></button></div>
      <div className="dashboard-grid"><section className="map-panel"><div className="section-heading"><div><span className="section-kicker"><span className="pulse-dot"></span>{t.tracking}</span><h2>Corridor situation</h2></div><div className="map-legend"><span><i className="legend-safe"></i>Safe</span><span><i className="legend-caution"></i>Caution</span><span><i className="legend-danger"></i>High risk</span></div></div><div className="map-frame"><MapContainer center={[25.5,92.9]} zoom={7} scrollWheelZoom={false} zoomControl={false}><Recenter position={state === "All states" ? [25.5,92.9] : (filteredRoutes[0]?.points[0] || [25.5,92.9])}/><TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{filteredRoutes.map(route => <Polyline key={route.id} positions={route.points} pathOptions={{color:riskColor(route.risk), weight:route.risk > 60 ? 5 : 3, opacity:.9, dashArray:route.risk > 60 ? "8 8" : undefined}}><Popup><strong>{route.id}</strong><br/>Risk {route.risk} · Accessibility {route.accessibility}</Popup></Polyline>)}{filteredVehicles.map(vehicle => <CircleMarker key={vehicle.id} center={vehicle.position} radius={7} pathOptions={{color:"#fff", weight:2, fillColor:vehicle.status === "rerouted" ? "#f43f5e" : "#f97316", fillOpacity:1}}><Popup><strong>{vehicle.id}</strong><br/>{vehicle.payload}<br/>{vehicle.eta} · {vehicle.status}</Popup></CircleMarker>)}{data.incidents.filter(i => state === "All states" || i.state === state).map((incident, idx) => <CircleMarker key={idx} center={incident.location} radius={5} pathOptions={{color:"#f43f5e", fillColor:"#f43f5e", fillOpacity:.8}}><Popup>{incident.type} · {incident.state}<br/>{incident.time}</Popup></CircleMarker>)}</MapContainer><div className="map-overlay"><div><span>NETWORK RISK INDEX</span><strong>{Math.round(tRisk)}<small>/100</small></strong></div><div className="map-weather"><CloudRain size={17}/><span>Monsoon watch<br/><b>80–120 mm / 24h</b></span></div></div></div><div className="map-footnote"><span><LocateFixed size={14}/> Showing {filteredRoutes.length} corridors · {filteredVehicles.length} active vehicles</span><span>Auto-refresh 30s <i className="refresh-dot"></i></span></div></section>
        <aside className="side-column"><div className="panel-block"><div className="section-heading compact"><div><span className="section-kicker">LIVE SIGNALS</span><h2>{t.alerts}</h2></div><span className="count-badge" data-testid="active-alert-count">{activeIncidents.length.toString().padStart(2,"0")}</span></div><div className="alert-list">{activeIncidents.slice(0,3).map((incident, idx) => <AlertItem key={`${incident.time}-${idx}`} severity={incident.severity.toUpperCase() === "MEDIUM" ? "MED" : incident.severity.toUpperCase()} title={`${incident.type} · ${incident.state}`} text={`${incident.time} · ${incident.severity} priority`} />)}</div><button className="text-button" data-testid="view-all-alerts-button">View all alerts <ArrowUpRight size={15}/></button></div><div className="panel-block bottleneck-block"><div className="section-heading compact"><div><span className="section-kicker">RISK-WEIGHTED</span><h2>{t.bottlenecks}</h2></div><ArrowUpRight size={16}/></div>{filteredRoutes.sort((a,b)=>b.risk-a.risk).slice(0,3).map((route,idx)=><div className="route-row" key={route.id} data-testid={`bottleneck-route-${idx}`}><div className="route-rank">0{idx+1}</div><div className="route-info"><strong>{route.id.split(" / ")[0]}</strong><span>{route.state} · {route.delay} delay</span></div><div className="risk-number" style={{color:riskColor(route.risk)}}>{route.risk}</div></div>)}</div></aside></div>
      <section className="bottom-grid"><div className="delivery-panel"><div className="section-heading compact"><div><span className="section-kicker">MISSION CONTROL</span><h2>Delivery pulse</h2></div><button className="text-button" data-testid="delivery-details-button">Details <ArrowUpRight size={15}/></button></div><div className="delivery-stats"><div><strong>04</strong><span>In transit</span></div><div><strong>01</strong><span>Rerouted</span></div><div><strong>01</strong><span>Delivered</span></div><div><strong>87%</strong><span>On time</span></div></div><div className="vehicle-table"><div className="table-head"><span>VEHICLE</span><span>PAYLOAD</span><span>ROUTE</span><span>ETA</span><span>STATUS</span></div>{filteredVehicles.slice(0,4).map(v=><div className="table-row" key={v.id} data-testid={`vehicle-row-${v.id}`}><span><b className="vehicle-dot"></b>{v.id}<small>{v.type}</small></span><span>{v.payload}</span><span>{v.route.split(" /")[0]}</span><span>{v.eta}</span><span className={`status ${v.status.replace("-","")}`}>{v.status === "rerouted" ? t.rerouted : v.status === "in-transit" ? t.inTransit : t.delivered}</span></div>)}</div></div><div className="model-panel"><div className="section-kicker">PREDICTION ENGINE</div><h2>Signal confidence</h2><p>Rule-based scoring calibrated against synthetic incident history.</p><div className="confidence"><strong>{data.calibration.accuracy}%</strong><span>calibration<br/>accuracy</span><div className="confidence-ring"><span>{data.calibration.confidence}</span></div></div><div className="model-foot"><span><CheckCircle2 size={14}/> Transparent logic</span><span>v0.8.4</span></div></div></section>
    </section>
    {toast && <div className="toast" data-testid="alert-toast"><CheckCircle2 size={17}/>{toast}<button onClick={() => setToast("")} data-testid="close-toast-button"><X size={15}/></button></div>}
    {showReport && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setShowReport(false)}><form className="report-modal" onSubmit={submitReport}><div className="modal-head"><div><span className="section-kicker">OFFLINE-FIRST INTAKE</span><h2>{t.report}</h2></div><button type="button" className="icon-button" onClick={() => setShowReport(false)} data-testid="close-field-report-button"><X size={18}/></button></div><label>{t.incident}<select value={form.incident_type} onChange={e=>setForm({...form,incident_type:e.target.value})} data-testid="incident-type-input"><option>Landslide</option><option>Flooding</option><option>Road damage</option><option>Bridge collapse</option><option>Vehicle breakdown</option></select></label><div className="form-split"><label>{t.severity}<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} data-testid="severity-input"><option>High</option><option>Medium</option><option>Low</option></select></label><label>{t.state}<select value={form.state} onChange={e=>setForm({...form,state:e.target.value})} data-testid="report-state-input">{data.states.map(s=><option key={s}>{s}</option>)}</select></label></div><label>{t.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Describe what the field team sees…" data-testid="report-notes-input"/></label><label className="upload-box"><UploadCloud size={20}/><span>{t.upload}<small>JPG or PNG · stored offline until synced</small></span><input type="file" accept="image/*" onChange={e=>setForm({...form,image_data:e.target.files?.[0]?.name})} data-testid="damage-photo-input"/></label><div className="modal-actions"><span><Radio size={14}/> Mock GPS locked · {form.latitude}, {form.longitude}</span><button className="primary-button" type="submit" data-testid="submit-field-report-button"><Send size={15}/>{t.submit}</button></div></form></div>}
  </main>;
};
const Metric = ({icon,label,value,detail,tone}) => <div className={`metric metric-${tone}`} data-testid={`metric-${label.toLowerCase().replaceAll(" ","-")}`}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;
const AlertItem = ({severity,title,text}) => <div className="alert-item"><span className={`severity severity-${severity.toLowerCase()}`}>{severity}</span><div><strong>{title}</strong><p>{text}</p></div><ArrowUpRight size={14}/></div>;

function App() {
  return <Home />;
}

export default App;
